List datakab = [
  {"id": "0", "id_prov": "0", "nama": "Kabupaten"},
  {"id": "1", "id_prov": "1", "nama": "Kabupaten Gianyar"},
  {"id": "2", "id_prov": "1", "nama": "Kabupaten Bangli"},
  {"id": "3", "id_prov": "1", "nama": "Kabupaten Buleleng"},
  {"id": "4", "id_prov": "1", "nama": "Kabupaten Tabanan"},
  {"id": "5", "id_prov": "1", "nama": "Kabupaten Karangasem"},
  {"id": "6", "id_prov": "1", "nama": "Kabupaten Badung"},
  {"id": "7", "id_prov": "1", "nama": "Kabupaten Jembrana"},
  {"id": "8", "id_prov": "1", "nama": "Kabupaten Klungkung"},
  {"id": "9", "id_prov": "1", "nama": "Kota Denpasar"},
  {"id": "10", "id_prov": "2", "nama": "Kabupaten Bangka Selatan"},
  {"id": "11", "id_prov": "2", "nama": "Kabupaten Bangka Barat"},
  {"id": "12", "id_prov": "2", "nama": "Kabupaten Belitung"},
  {"id": "13", "id_prov": "2", "nama": "Kota Pangkal Pinang"},
  {"id": "14", "id_prov": "2", "nama": "Kabupaten Bangka Tengah"},
  {"id": "15", "id_prov": "2", "nama": "Kabupaten Bangka"},
  {"id": "16", "id_prov": "2", "nama": "Kabupaten Belitung Timur"},
  {"id": "17", "id_prov": "3", "nama": "Kabupaten Lebak"},
  {"id": "18", "id_prov": "3", "nama": "Kabupaten Serang"},
  {"id": "19", "id_prov": "3", "nama": "Kota Serang"},
  {"id": "20", "id_prov": "3", "nama": "Kabupaten Tangerang"},
  {"id": "21", "id_prov": "3", "nama": "Kota Tangerang"},
  {"id": "22", "id_prov": "3", "nama": "Kabupaten Pandeglang"},
  {"id": "23", "id_prov": "3", "nama": "Kota Tangerang Selatan"},
  {"id": "24", "id_prov": "3", "nama": "Kota Cilegon"},
  {"id": "25", "id_prov": "4", "nama": "Kabupaten Seluma"},
  {"id": "26", "id_prov": "4", "nama": "Kabupaten Bengkulu Tengah"},
  {"id": "27", "id_prov": "4", "nama": "Kota Bengkulu"},
  {"id": "28", "id_prov": "4", "nama": "Kabupaten Muko Muko"},
  {"id": "29", "id_prov": "4", "nama": "Kabupaten Rejang Lebong"},
  {"id": "30", "id_prov": "4", "nama": "Kabupaten Kaur"},
  {"id": "31", "id_prov": "4", "nama": "Kabupaten Bengkulu Selatan"},
  {"id": "32", "id_prov": "4", "nama": "Kabupaten Kepahiang"},
  {"id": "33", "id_prov": "4", "nama": "Kabupaten Lebong"},
  {"id": "34", "id_prov": "4", "nama": "Kabupaten Bengkulu Utara"},
  {"id": "35", "id_prov": "5", "nama": "Kabupaten Gunung Kidul"},
  {"id": "36", "id_prov": "5", "nama": "Kota Yogyakarta"},
  {"id": "37", "id_prov": "5", "nama": "Kabupaten Kulon Progo"},
  {"id": "38", "id_prov": "5", "nama": "Kabupaten Sleman"},
  {"id": "39", "id_prov": "5", "nama": "Kabupaten Bantul"},
  {"id": "40", "id_prov": "6", "nama": "Kota Jakarta Selatan"},
  {"id": "41", "id_prov": "6", "nama": "Kota Jakarta Utara"},
  {"id": "42", "id_prov": "6", "nama": "Kota Jakarta Pusat"},
  {"id": "43", "id_prov": "6", "nama": "Kota Jakarta Barat"},
  {"id": "44", "id_prov": "6", "nama": "Kota Jakarta Timur"},
  {"id": "45", "id_prov": "6", "nama": "Kabupaten Kepulauan Seribu"},
  {"id": "46", "id_prov": "7", "nama": "Kabupaten Boalemo"},
  {"id": "47", "id_prov": "7", "nama": "Kabupaten Pohuwato"},
  {"id": "48", "id_prov": "7", "nama": "Kabupaten Gorontalo Utara"},
  {"id": "49", "id_prov": "7", "nama": "Kabupaten Gorontalo"},
  {"id": "50", "id_prov": "7", "nama": "Kabupaten Bone Bolango"},
  {"id": "51", "id_prov": "7", "nama": "Kota Gorontalo"},
  {"id": "52", "id_prov": "8", "nama": "Kabupaten Tebo"},
  {"id": "53", "id_prov": "8", "nama": "Kabupaten Tanjung Jabung Barat"},
  {"id": "54", "id_prov": "8", "nama": "Kabupaten Merangin"},
  {"id": "55", "id_prov": "8", "nama": "Kota Jambi"},
  {"id": "56", "id_prov": "8", "nama": "Kabupaten Bungo"},
  {"id": "57", "id_prov": "8", "nama": "Kota Sungaipenuh"},
  {"id": "58", "id_prov": "8", "nama": "Kabupaten Muaro Jambi"},
  {"id": "59", "id_prov": "8", "nama": "Kabupaten Kerinci"},
  {"id": "60", "id_prov": "8", "nama": "Kabupaten Sarolangun"},
  {"id": "61", "id_prov": "8", "nama": "Kabupaten Tanjung Jabung Timur"},
  {"id": "62", "id_prov": "8", "nama": "Kabupaten Batang Hari"},
  {"id": "63", "id_prov": "9", "nama": "Kabupaten Indramayu"},
  {"id": "64", "id_prov": "9", "nama": "Kabupaten Cirebon"},
  {"id": "65", "id_prov": "9", "nama": "Kabupaten Cianjur"},
  {"id": "66", "id_prov": "9", "nama": "Kabupaten Sukabumi"},
  {"id": "67", "id_prov": "9", "nama": "Kota Sukabumi"},
  {"id": "68", "id_prov": "9", "nama": "Kabupaten Purwakarta"},
  {"id": "69", "id_prov": "9", "nama": "Kabupaten Garut"},
  {"id": "70", "id_prov": "9", "nama": "Kabupaten Sumedang"},
  {"id": "71", "id_prov": "9", "nama": "Kota Bandung"},
  {"id": "72", "id_prov": "9", "nama": "Kabupaten Karawang"},
  {"id": "73", "id_prov": "9", "nama": "Kabupaten Bogor"},
  {"id": "74", "id_prov": "9", "nama": "Kota Tasikmalaya"},
  {"id": "75", "id_prov": "9", "nama": "Kabupaten Bekasi"},
  {"id": "76", "id_prov": "9", "nama": "Kabupaten Tasikmalaya"},
  {"id": "77", "id_prov": "9", "nama": "Kota Depok"},
  {"id": "78", "id_prov": "9", "nama": "Kabupaten Subang"},
  {"id": "79", "id_prov": "9", "nama": "Kota Bogor"},
  {"id": "80", "id_prov": "9", "nama": "Kabupaten Ciamis"},
  {"id": "81", "id_prov": "9", "nama": "Kabupaten Majalengka"},
  {"id": "82", "id_prov": "9", "nama": "Kabupaten Kuningan"},
  {"id": "83", "id_prov": "9", "nama": "Kabupaten Bandung"},
  {"id": "84", "id_prov": "9", "nama": "Kabupaten Bandung Barat"},
  {"id": "85", "id_prov": "9", "nama": "Kabupaten Pangandaran"},
  {"id": "86", "id_prov": "9", "nama": "Kota Bekasi"},
  {"id": "87", "id_prov": "9", "nama": "Kota Banjar"},
  {"id": "88", "id_prov": "9", "nama": "Kota Cirebon"},
  {"id": "89", "id_prov": "9", "nama": "Kota Cimahi"},
  {"id": "90", "id_prov": "10", "nama": "Kabupaten Wonogiri"},
  {"id": "91", "id_prov": "10", "nama": "Kabupaten Batang"},
  {"id": "92", "id_prov": "10", "nama": "Kabupaten Wonosobo"},
  {"id": "93", "id_prov": "10", "nama": "Kabupaten Boyolali"},
  {"id": "94", "id_prov": "10", "nama": "Kabupaten Klaten"},
  {"id": "95", "id_prov": "10", "nama": "Kabupaten Demak"},
  {"id": "96", "id_prov": "10", "nama": "Kabupaten Pekalongan"},
  {"id": "97", "id_prov": "10", "nama": "Kabupaten Temanggung"},
  {"id": "98", "id_prov": "10", "nama": "Kabupaten Grobogan"},
  {"id": "99", "id_prov": "10", "nama": "Kabupaten Pati"},
  {"id": "100", "id_prov": "10", "nama": "Kabupaten Magelang"},
  {"id": "101", "id_prov": "10", "nama": "Kabupaten Sukoharjo"},
  {"id": "102", "id_prov": "10", "nama": "Kabupaten Kendal"},
  {"id": "103", "id_prov": "10", "nama": "Kabupaten Jepara"},
  {"id": "104", "id_prov": "10", "nama": "Kabupaten Pemalang"},
  {"id": "105", "id_prov": "10", "nama": "Kabupaten Tegal"},
  {"id": "106", "id_prov": "10", "nama": "Kabupaten Banyumas"},
  {"id": "107", "id_prov": "10", "nama": "Kabupaten Banjarnegara"},
  {"id": "108", "id_prov": "10", "nama": "Kabupaten Brebes"},
  {"id": "109", "id_prov": "10", "nama": "Kabupaten Cilacap"},
  {"id": "110", "id_prov": "10", "nama": "Kabupaten Semarang"},
  {"id": "111", "id_prov": "10", "nama": "Kabupaten Kudus"},
  {"id": "112", "id_prov": "10", "nama": "Kabupaten Blora"},
  {"id": "113", "id_prov": "10", "nama": "Kota Semarang"},
  {"id": "114", "id_prov": "10", "nama": "Kota Salatiga"},
  {"id": "115", "id_prov": "10", "nama": "Kota Tegal"},
  {"id": "116", "id_prov": "10", "nama": "Kabupaten Karanganyar"},
  {"id": "117", "id_prov": "10", "nama": "Kabupaten Sragen"},
  {"id": "118", "id_prov": "10", "nama": "Kabupaten Rembang"},
  {"id": "119", "id_prov": "10", "nama": "Kabupaten Kebumen"},
  {"id": "120", "id_prov": "10", "nama": "Kota Surakarta"},
  {"id": "121", "id_prov": "10", "nama": "Kabupaten Purbalingga"},
  {"id": "122", "id_prov": "10", "nama": "Kabupaten Purworejo"},
  {"id": "123", "id_prov": "10", "nama": "Kota Pekalongan"},
  {"id": "124", "id_prov": "10", "nama": "Kota Magelang"},
  {"id": "125", "id_prov": "11", "nama": "Kabupaten Bangkalan"},
  {"id": "126", "id_prov": "11", "nama": "Kabupaten Banyuwangi"},
  {"id": "127", "id_prov": "11", "nama": "Kota Batu"},
  {"id": "128", "id_prov": "11", "nama": "Kota Blitar"},
  {"id": "129", "id_prov": "11", "nama": "Kabupaten Blitar"},
  {"id": "130", "id_prov": "11", "nama": "Kabupaten Bojonegoro"},
  {"id": "131", "id_prov": "11", "nama": "Kabupaten Bondowoso"},
  {"id": "132", "id_prov": "11", "nama": "Kabupaten Gresik"},
  {"id": "133", "id_prov": "11", "nama": "Kabupaten Jember"},
  {"id": "134", "id_prov": "11", "nama": "Kabupaten Jombang"},
  {"id": "135", "id_prov": "11", "nama": "Kota Kediri"},
  {"id": "136", "id_prov": "11", "nama": "Kabupaten Kediri"},
  {"id": "137", "id_prov": "11", "nama": "Kabupaten Lamongan"},
  {"id": "138", "id_prov": "11", "nama": "Kabupaten Lumajang"},
  {"id": "139", "id_prov": "11", "nama": "Kota Madiun"},
  {"id": "140", "id_prov": "11", "nama": "Kabupaten Madiun"},
  {"id": "141", "id_prov": "11", "nama": "Kabupaten Magetan"},
  {"id": "142", "id_prov": "11", "nama": "Kota Malang"},
  {"id": "143", "id_prov": "11", "nama": "Kabupaten Malang"},
  {"id": "144", "id_prov": "11", "nama": "Kota Mojokerto"},
  {"id": "145", "id_prov": "11", "nama": "Kabupaten Mojokerto"},
  {"id": "146", "id_prov": "11", "nama": "Kabupaten Nganjuk"},
  {"id": "147", "id_prov": "11", "nama": "Kabupaten Ngawi"},
  {"id": "148", "id_prov": "11", "nama": "Kabupaten Pacitan"},
  {"id": "149", "id_prov": "11", "nama": "Kabupaten Pamekasan"},
  {"id": "150", "id_prov": "11", "nama": "Kota Pasuruan"},
  {"id": "151", "id_prov": "11", "nama": "Kabupaten Pasuruan"},
  {"id": "152", "id_prov": "11", "nama": "Kabupaten Ponorogo"},
  {"id": "153", "id_prov": "11", "nama": "Kota Probolinggo"},
  {"id": "154", "id_prov": "11", "nama": "Kabupaten Probolinggo"},
  {"id": "155", "id_prov": "11", "nama": "Kabupaten Sampang"},
  {"id": "156", "id_prov": "11", "nama": "Kabupaten Sidoarjo"},
  {"id": "157", "id_prov": "11", "nama": "Kabupaten Situbondo"},
  {"id": "158", "id_prov": "11", "nama": "Kabupaten Sumenep"},
  {"id": "159", "id_prov": "11", "nama": "Kota Surabaya"},
  {"id": "160", "id_prov": "11", "nama": "Kabupaten Trenggalek"},
  {"id": "161", "id_prov": "11", "nama": "Kabupaten Tuban"},
  {"id": "162", "id_prov": "11", "nama": "Kabupaten Tulungagung"},
  {"id": "163", "id_prov": "12", "nama": "Kabupaten Bengkayang"},
  {"id": "164", "id_prov": "12", "nama": "Kabupaten Kapuas Hulu"},
  {"id": "165", "id_prov": "12", "nama": "Kabupaten Kayong Utara"},
  {"id": "166", "id_prov": "12", "nama": "Kabupaten Ketapang"},
  {"id": "167", "id_prov": "12", "nama": "Kabupaten Kubu Raya"},
  {"id": "168", "id_prov": "12", "nama": "Kabupaten Landak"},
  {"id": "169", "id_prov": "12", "nama": "Kabupaten Melawi"},
  {"id": "170", "id_prov": "12", "nama": "Kabupaten Mempawah"},
  {"id": "171", "id_prov": "12", "nama": "Kota Pontianak"},
  {"id": "172", "id_prov": "12", "nama": "Kabupaten Sambas"},
  {"id": "173", "id_prov": "12", "nama": "Kabupaten Sanggau"},
  {"id": "174", "id_prov": "12", "nama": "Kabupaten Sekadau"},
  {"id": "175", "id_prov": "12", "nama": "Kota Singkawang"},
  {"id": "176", "id_prov": "12", "nama": "Kabupaten Sintang"},
  {"id": "177", "id_prov": "13", "nama": "Kabupaten Balangan"},
  {"id": "178", "id_prov": "13", "nama": "Kabupaten Banjar"},
  {"id": "179", "id_prov": "13", "nama": "Kota Banjarbaru"},
  {"id": "180", "id_prov": "13", "nama": "Kota Banjarmasin"},
  {"id": "181", "id_prov": "13", "nama": "Kabupaten Barito Kuala"},
  {"id": "182", "id_prov": "13", "nama": "Kabupaten Hulu Sungai Selatan"},
  {"id": "183", "id_prov": "13", "nama": "Kabupaten Hulu Sungai Tengah"},
  {"id": "184", "id_prov": "13", "nama": "Kabupaten Hulu Sungai Utara"},
  {"id": "185", "id_prov": "13", "nama": "Kabupaten Kotabaru"},
  {"id": "186", "id_prov": "13", "nama": "Kabupaten Tabalong"},
  {"id": "187", "id_prov": "13", "nama": "Kabupaten Tanah Bumbu"},
  {"id": "188", "id_prov": "13", "nama": "Kabupaten Tanah Laut"},
  {"id": "189", "id_prov": "13", "nama": "Kabupaten Tapin"},
  {"id": "190", "id_prov": "14", "nama": "Kabupaten Barito Selatan"},
  {"id": "191", "id_prov": "14", "nama": "Kabupaten Barito Timur"},
  {"id": "192", "id_prov": "14", "nama": "Kabupaten Barito Utara"},
  {"id": "193", "id_prov": "14", "nama": "Kabupaten Gunung Mas"},
  {"id": "194", "id_prov": "14", "nama": "Kabupaten Kapuas"},
  {"id": "195", "id_prov": "14", "nama": "Kabupaten Katingan"},
  {"id": "196", "id_prov": "14", "nama": "Kabupaten Kotawaringin Barat"},
  {"id": "197", "id_prov": "14", "nama": "Kabupaten Kotawaringin Timur"},
  {"id": "198", "id_prov": "14", "nama": "Kabupaten Lamandau"},
  {"id": "199", "id_prov": "14", "nama": "Kabupaten Murung Raya"},
  {"id": "200", "id_prov": "14", "nama": "Kota Palangka Raya"},
  {"id": "201", "id_prov": "14", "nama": "Kabupaten Pulang Pisau"},
  {"id": "202", "id_prov": "14", "nama": "Kabupaten Seruyan"},
  {"id": "203", "id_prov": "14", "nama": "Kabupaten Sukamara"},
  {"id": "204", "id_prov": "15", "nama": "Kota Balikpapan"},
  {"id": "205", "id_prov": "15", "nama": "Kabupaten Berau"},
  {"id": "206", "id_prov": "15", "nama": "Kota Bontang"},
  {"id": "207", "id_prov": "15", "nama": "Kabupaten Kutai Barat"},
  {"id": "208", "id_prov": "15", "nama": "Kabupaten Kutai Kartanegara"},
  {"id": "209", "id_prov": "15", "nama": "Kabupaten Kutai Timur"},
  {"id": "210", "id_prov": "15", "nama": "Kabupaten Mahakam Ulu"},
  {"id": "211", "id_prov": "15", "nama": "Kabupaten Paser"},
  {"id": "212", "id_prov": "15", "nama": "Kabupaten Penajam Paser Utara"},
  {"id": "213", "id_prov": "15", "nama": "Kota Samarinda"},
  {"id": "214", "id_prov": "16", "nama": "Kabupaten Bulungan"},
  {"id": "215", "id_prov": "16", "nama": "Kabupaten Malinau"},
  {"id": "216", "id_prov": "16", "nama": "Kabupaten Nunukan"},
  {"id": "217", "id_prov": "16", "nama": "Kabupaten Tana Tidung"},
  {"id": "218", "id_prov": "16", "nama": "Kota Tarakan"},
  {"id": "219", "id_prov": "17", "nama": "Kota Batam"},
  {"id": "220", "id_prov": "17", "nama": "Kabupaten Bintan"},
  {"id": "221", "id_prov": "17", "nama": "Kabupaten Karimun"},
  {"id": "222", "id_prov": "17", "nama": "Kabupaten Kepulauan Anambas"},
  {"id": "223", "id_prov": "17", "nama": "Kabupaten Lingga"},
  {"id": "224", "id_prov": "17", "nama": "Kabupaten Natuna"},
  {"id": "225", "id_prov": "17", "nama": "Kota Tanjung Pinang"},
  {"id": "226", "id_prov": "18", "nama": "Kota Bandar Lampung"},
  {"id": "227", "id_prov": "18", "nama": "Kabupaten Lampung Barat"},
  {"id": "228", "id_prov": "18", "nama": "Kabupaten Lampung Selatan"},
  {"id": "229", "id_prov": "18", "nama": "Kabupaten Lampung Tengah"},
  {"id": "230", "id_prov": "18", "nama": "Kabupaten Lampung Timur"},
  {"id": "231", "id_prov": "18", "nama": "Kabupaten Lampung Utara"},
  {"id": "232", "id_prov": "18", "nama": "Kabupaten Mesuji"},
  {"id": "233", "id_prov": "18", "nama": "Kota Metro"},
  {"id": "234", "id_prov": "18", "nama": "Kabupaten Pesawaran"},
  {"id": "235", "id_prov": "18", "nama": "Kabupaten Pesisir Barat"},
  {"id": "236", "id_prov": "18", "nama": "Kabupaten Pringsewu"},
  {"id": "237", "id_prov": "18", "nama": "Kabupaten Tanggamus"},
  {"id": "238", "id_prov": "18", "nama": "Kabupaten Tulang Bawang"},
  {"id": "239", "id_prov": "18", "nama": "Kabupaten Tulang Bawang Barat"},
  {"id": "240", "id_prov": "18", "nama": "Kabupaten Way Kanan"},
  {"id": "241", "id_prov": "19", "nama": "Kota Ambon"},
  {"id": "242", "id_prov": "19", "nama": "Kabupaten Buru"},
  {"id": "243", "id_prov": "19", "nama": "Kabupaten Buru Selatan"},
  {"id": "244", "id_prov": "19", "nama": "Kabupaten Kepulauan Aru"},
  {"id": "245", "id_prov": "19", "nama": "Kabupaten Maluku Barat Daya"},
  {"id": "246", "id_prov": "19", "nama": "Kabupaten Maluku Tengah"},
  {"id": "247", "id_prov": "19", "nama": "Kabupaten Maluku Tenggara"},
  {"id": "248", "id_prov": "19", "nama": "Kabupaten Maluku Tenggara Barat"},
  {"id": "249", "id_prov": "19", "nama": "Kabupaten Seram Bagian Barat"},
  {"id": "250", "id_prov": "19", "nama": "Kabupaten Seram Bagian Timur"},
  {"id": "251", "id_prov": "19", "nama": "Kota Tual"},
  {"id": "252", "id_prov": "20", "nama": "Kabupaten Halmahera Barat"},
  {"id": "253", "id_prov": "20", "nama": "Kabupaten Halmahera Selatan"},
  {"id": "254", "id_prov": "20", "nama": "Kabupaten Halmahera Tengah"},
  {"id": "255", "id_prov": "20", "nama": "Kabupaten Halmahera Timur"},
  {"id": "256", "id_prov": "20", "nama": "Kabupaten Halmahera Utara"},
  {"id": "257", "id_prov": "20", "nama": "Kabupaten Kepulauan Sula"},
  {"id": "258", "id_prov": "20", "nama": "Kabupaten Pulau Morotai"},
  {"id": "259", "id_prov": "20", "nama": "Kabupaten Pulau Taliabu"},
  {"id": "260", "id_prov": "20", "nama": "Kota Ternate"},
  {"id": "261", "id_prov": "20", "nama": "Kota Tidore Kepulauan"},
  {"id": "262", "id_prov": "21", "nama": "Kabupaten Aceh Barat"},
  {"id": "263", "id_prov": "21", "nama": "Kabupaten Aceh Barat Daya"},
  {"id": "264", "id_prov": "21", "nama": "Kabupaten Aceh Besar"},
  {"id": "265", "id_prov": "21", "nama": "Kabupaten Aceh Jaya"},
  {"id": "266", "id_prov": "21", "nama": "Kabupaten Aceh Selatan"},
  {"id": "267", "id_prov": "21", "nama": "Kabupaten Aceh Singkil"},
  {"id": "268", "id_prov": "21", "nama": "Kabupaten Aceh Tamiang"},
  {"id": "269", "id_prov": "21", "nama": "Kabupaten Aceh Tengah"},
  {"id": "270", "id_prov": "21", "nama": "Kabupaten Aceh Tenggara"},
  {"id": "271", "id_prov": "21", "nama": "Kabupaten Aceh Timur"},
  {"id": "272", "id_prov": "21", "nama": "Kabupaten Aceh Utara"},
  {"id": "273", "id_prov": "21", "nama": "Kota Banda Aceh"},
  {"id": "274", "id_prov": "21", "nama": "Kabupaten Bener Meriah"},
  {"id": "275", "id_prov": "21", "nama": "Kabupaten Bireuen"},
  {"id": "276", "id_prov": "21", "nama": "Kabupaten Gayo Lues"},
  {"id": "277", "id_prov": "21", "nama": "Kota Lhokseumawe"},
  {"id": "278", "id_prov": "21", "nama": "Kabupaten Nagan Raya"},
  {"id": "279", "id_prov": "21", "nama": "Kabupaten Pidie"},
  {"id": "280", "id_prov": "21", "nama": "Kabupaten Pidie Jaya"},
  {"id": "281", "id_prov": "21", "nama": "Kota Sabang"},
  {"id": "282", "id_prov": "21", "nama": "Kabupaten Simeulue"},
  {"id": "283", "id_prov": "21", "nama": "Kota Subulussalam"},
  {"id": "284", "id_prov": "22", "nama": "Kota Bima"},
  {"id": "285", "id_prov": "22", "nama": "Kabupaten Bima"},
  {"id": "286", "id_prov": "22", "nama": "Kabupaten Dompu"},
  {"id": "287", "id_prov": "22", "nama": "Kabupaten Lombok Barat"},
  {"id": "288", "id_prov": "22", "nama": "Kabupaten Lombok Tengah"},
  {"id": "289", "id_prov": "22", "nama": "Kabupaten Lombok Timur"},
  {"id": "290", "id_prov": "22", "nama": "Kabupaten Lombok Utara"},
  {"id": "291", "id_prov": "22", "nama": "Kota Mataram"},
  {"id": "292", "id_prov": "22", "nama": "Kabupaten Sumbawa"},
  {"id": "293", "id_prov": "22", "nama": "Kabupaten Sumbawa Barat"},
  {"id": "294", "id_prov": "23", "nama": "Kabupaten Alor"},
  {"id": "295", "id_prov": "23", "nama": "Kabupaten Belu"},
  {"id": "296", "id_prov": "23", "nama": "Kabupaten Ende"},
  {"id": "297", "id_prov": "23", "nama": "Kabupaten  Ende"},
  {"id": "298", "id_prov": "23", "nama": "Kabupaten  Flores Timur"},
  {"id": "299", "id_prov": "23", "nama": "Kabupaten Flores Timur"},
  {"id": "300", "id_prov": "23", "nama": "Kota Kupang"},
  {"id": "301", "id_prov": "23", "nama": "Kabupaten Kupang"},
  {"id": "302", "id_prov": "23", "nama": "Kabupaten Lembata"},
  {"id": "303", "id_prov": "23", "nama": "Kabupaten Malaka"},
  {"id": "304", "id_prov": "23", "nama": "Kabupaten Manggarai"},
  {"id": "305", "id_prov": "23", "nama": "Kabupaten Manggarai Barat"},
  {"id": "306", "id_prov": "23", "nama": "Kabupaten Manggarai Timur"},
  {"id": "307", "id_prov": "23", "nama": "Kabupaten Nagekeo"},
  {"id": "308", "id_prov": "23", "nama": "Kabupaten Ngada"},
  {"id": "309", "id_prov": "23", "nama": "Kabupaten Rote Ndao"},
  {"id": "310", "id_prov": "23", "nama": "Kabupaten Sabu Raijua"},
  {"id": "311", "id_prov": "23", "nama": "Kabupaten Sikka"},
  {"id": "312", "id_prov": "23", "nama": "Kabupaten Sumba Barat"},
  {"id": "313", "id_prov": "23", "nama": "Kabupaten Sumba Barat Daya"},
  {"id": "314", "id_prov": "23", "nama": "Kabupaten Sumba Tengah"},
  {"id": "315", "id_prov": "23", "nama": "Kabupaten Sumba Timur"},
  {"id": "316", "id_prov": "23", "nama": "Kabupaten Timor Tengah Selatan"},
  {"id": "317", "id_prov": "23", "nama": "Kabupaten Timor Tengah Utara"},
  {"id": "318", "id_prov": "24", "nama": "Kabupaten Asmat"},
  {"id": "319", "id_prov": "24", "nama": "Kabupaten Biak Numfor"},
  {"id": "320", "id_prov": "24", "nama": "Kabupaten Boven Digoel"},
  {"id": "321", "id_prov": "24", "nama": "Kabupaten Deiyai"},
  {"id": "322", "id_prov": "24", "nama": "Kabupaten Dogiyai"},
  {"id": "323", "id_prov": "24", "nama": "Kabupaten Intan Jaya"},
  {"id": "324", "id_prov": "24", "nama": "Kota Jayapura"},
  {"id": "325", "id_prov": "24", "nama": "Kabupaten Jayapura"},
  {"id": "326", "id_prov": "24", "nama": "Kabupaten Jayawijaya"},
  {"id": "327", "id_prov": "24", "nama": "Kabupaten Keerom"},
  {"id": "328", "id_prov": "24", "nama": "Kabupaten Kepulauan Yapen"},
  {"id": "329", "id_prov": "24", "nama": "Kabupaten Lanny Jaya"},
  {"id": "330", "id_prov": "24", "nama": "Kabupaten Mamberamo Raya"},
  {"id": "331", "id_prov": "24", "nama": "Kabupaten Mamberamo Tengah"},
  {"id": "332", "id_prov": "24", "nama": "Kabupaten Mappi"},
  {"id": "333", "id_prov": "24", "nama": "Kabupaten Merauke"},
  {"id": "334", "id_prov": "24", "nama": "Kabupaten Mimika"},
  {"id": "335", "id_prov": "24", "nama": "Kabupaten Nabire"},
  {"id": "336", "id_prov": "24", "nama": "Kabupaten Nduga"},
  {"id": "337", "id_prov": "24", "nama": "Kabupaten Paniai"},
  {"id": "338", "id_prov": "24", "nama": "Kabupaten Pegunungan Bintang"},
  {"id": "339", "id_prov": "24", "nama": "Kabupaten Puncak"},
  {"id": "340", "id_prov": "24", "nama": "Kabupaten Puncak Jaya"},
  {"id": "341", "id_prov": "24", "nama": "Kabupaten Sarmi"},
  {"id": "342", "id_prov": "24", "nama": "Kabupaten Supiori"},
  {"id": "343", "id_prov": "24", "nama": "Kabupaten Tolikara"},
  {"id": "344", "id_prov": "24", "nama": "Kabupaten Waropen"},
  {"id": "345", "id_prov": "24", "nama": "Kabupaten Yahukimo"},
  {"id": "346", "id_prov": "24", "nama": "Kabupaten Yalimo"},
  {"id": "347", "id_prov": "25", "nama": "Kabupaten Fakfak"},
  {"id": "348", "id_prov": "25", "nama": "Kabupaten Kaimana"},
  {"id": "349", "id_prov": "25", "nama": "Kabupaten Manokwari"},
  {"id": "350", "id_prov": "25", "nama": "Kabupaten Manokwari Selatan"},
  {"id": "351", "id_prov": "25", "nama": "Kabupaten Maybrat"},
  {"id": "352", "id_prov": "25", "nama": "Kabupaten Pegunungan Arfak"},
  {"id": "353", "id_prov": "25", "nama": "Kabupaten Raja Ampat"},
  {"id": "354", "id_prov": "25", "nama": "Kota Sorong"},
  {"id": "355", "id_prov": "25", "nama": "Kabupaten Sorong"},
  {"id": "356", "id_prov": "25", "nama": "Kabupaten Sorong Selatan"},
  {"id": "357", "id_prov": "25", "nama": "Kabupaten Tambrauw"},
  {"id": "358", "id_prov": "25", "nama": "Kabupaten Teluk Bintuni"},
  {"id": "359", "id_prov": "25", "nama": "Kabupaten Teluk Wondama"},
  {"id": "360", "id_prov": "26", "nama": "Kabupaten Bengkalis"},
  {"id": "361", "id_prov": "26", "nama": "Kota Dumai"},
  {"id": "362", "id_prov": "26", "nama": "Kabupaten Indragiri Hilir"},
  {"id": "363", "id_prov": "26", "nama": "Kabupaten Indragiri Hulu"},
  {"id": "364", "id_prov": "26", "nama": "Kabupaten Kampar"},
  {"id": "365", "id_prov": "26", "nama": "Kabupaten Kepulauan Meranti"},
  {"id": "366", "id_prov": "26", "nama": "Kabupaten Kuantan Singingi"},
  {"id": "367", "id_prov": "26", "nama": "Kota Pekanbaru"},
  {"id": "368", "id_prov": "26", "nama": "Kabupaten Pelalawan"},
  {"id": "369", "id_prov": "26", "nama": "Kabupaten Rokan Hilir"},
  {"id": "370", "id_prov": "26", "nama": "Kabupaten Rokan Hulu"},
  {"id": "371", "id_prov": "26", "nama": "Kabupaten Siak"},
  {"id": "372", "id_prov": "27", "nama": "Kabupaten Majene"},
  {"id": "373", "id_prov": "27", "nama": "Kabupaten Mamasa"},
  {"id": "374", "id_prov": "27", "nama": "Kabupaten Mamuju"},
  {"id": "375", "id_prov": "27", "nama": "Kabupaten Mamuju Tengah"},
  {"id": "376", "id_prov": "27", "nama": "Kabupaten Mamuju Utara"},
  {"id": "377", "id_prov": "27", "nama": "Kabupaten Polewali Mandar"},
  {"id": "378", "id_prov": "28", "nama": "Kabupaten Bantaeng"},
  {"id": "379", "id_prov": "28", "nama": "Kabupaten Barru"},
  {"id": "380", "id_prov": "28", "nama": "Kabupaten Bone"},
  {"id": "381", "id_prov": "28", "nama": "Kabupaten Bulukumba"},
  {"id": "382", "id_prov": "28", "nama": "Kabupaten Enrekang"},
  {"id": "383", "id_prov": "28", "nama": "Kabupaten Gowa"},
  {"id": "384", "id_prov": "28", "nama": "Kabupaten Jeneponto"},
  {"id": "385", "id_prov": "28", "nama": "Kabupaten Kepulauan Selayar"},
  {"id": "386", "id_prov": "28", "nama": "Kabupaten Luwu"},
  {"id": "387", "id_prov": "28", "nama": "Kabupaten Luwu Timur"},
  {"id": "388", "id_prov": "28", "nama": "Kabupaten Luwu Utara"},
  {"id": "389", "id_prov": "28", "nama": "Kota Makassar"},
  {"id": "390", "id_prov": "28", "nama": "Kabupaten Maros"},
  {"id": "391", "id_prov": "28", "nama": "Kota Palopo"},
  {"id": "392", "id_prov": "28", "nama": "Kabupaten Pangkajene Kepulauan"},
  {"id": "393", "id_prov": "28", "nama": "Kota Parepare"},
  {"id": "394", "id_prov": "28", "nama": "Kabupaten Pinrang"},
  {"id": "395", "id_prov": "28", "nama": "Kabupaten Sidenreng Rappang"},
  {"id": "396", "id_prov": "28", "nama": "Kabupaten Sinjai"},
  {"id": "397", "id_prov": "28", "nama": "Kabupaten Soppeng"},
  {"id": "398", "id_prov": "28", "nama": "Kabupaten Takalar"},
  {"id": "399", "id_prov": "28", "nama": "Kabupaten Tana Toraja"},
  {"id": "400", "id_prov": "28", "nama": "Kabupaten Toraja Utara"},
  {"id": "401", "id_prov": "28", "nama": "Kabupaten Wajo"},
  {"id": "402", "id_prov": "29", "nama": "Kabupaten Banggai"},
  {"id": "403", "id_prov": "29", "nama": "Kabupaten Banggai Kepulauan"},
  {"id": "404", "id_prov": "29", "nama": "Kabupaten Banggai Laut"},
  {"id": "405", "id_prov": "29", "nama": "Kabupaten Buol"},
  {"id": "406", "id_prov": "29", "nama": "Kabupaten Donggala"},
  {"id": "407", "id_prov": "29", "nama": "Kabupaten Morowali"},
  {"id": "408", "id_prov": "29", "nama": "Kabupaten Morowali Utara"},
  {"id": "409", "id_prov": "29", "nama": "Kota Palu"},
  {"id": "410", "id_prov": "29", "nama": "Kabupaten Parigi Moutong"},
  {"id": "411", "id_prov": "29", "nama": "Kabupaten Poso"},
  {"id": "412", "id_prov": "29", "nama": "Kabupaten Sigi"},
  {"id": "413", "id_prov": "29", "nama": "Kabupaten Tojo Una-Una"},
  {"id": "414", "id_prov": "29", "nama": "Kabupaten Toli-Toli"},
  {"id": "415", "id_prov": "30", "nama": "Kota Bau-Bau"},
  {"id": "416", "id_prov": "30", "nama": "Kabupaten Bombana"},
  {"id": "417", "id_prov": "30", "nama": "Kabupaten Buton"},
  {"id": "418", "id_prov": "30", "nama": "Kabupaten Buton Selatan"},
  {"id": "419", "id_prov": "30", "nama": "Kabupaten Buton Tengah"},
  {"id": "420", "id_prov": "30", "nama": "Kabupaten Buton Utara"},
  {"id": "421", "id_prov": "30", "nama": "Kota Kendari"},
  {"id": "422", "id_prov": "30", "nama": "Kabupaten Kolaka"},
  {"id": "423", "id_prov": "30", "nama": "Kabupaten Kolaka Timur"},
  {"id": "424", "id_prov": "30", "nama": "Kabupaten Kolaka Utara"},
  {"id": "425", "id_prov": "30", "nama": "Kabupaten Konawe"},
  {"id": "426", "id_prov": "30", "nama": "Kabupaten Konawe Kepulauan"},
  {"id": "427", "id_prov": "30", "nama": "Kabupaten Konawe Selatan"},
  {"id": "428", "id_prov": "30", "nama": "Kabupaten Konawe Utara"},
  {"id": "429", "id_prov": "30", "nama": "Kabupaten Muna"},
  {"id": "430", "id_prov": "30", "nama": "Kabupaten Muna Barat"},
  {"id": "431", "id_prov": "30", "nama": "Kabupaten Wakatobi"},
  {"id": "432", "id_prov": "31", "nama": "Kota Bitung"},
  {"id": "433", "id_prov": "31", "nama": "Kabupaten Bolaang Mongondow"},
  {"id": "434", "id_prov": "31", "nama": "Kabupaten Bolaang Mongondow Selatan"},
  {"id": "435", "id_prov": "31", "nama": "Kabupaten Bolaang Mongondow Timur"},
  {"id": "436", "id_prov": "31", "nama": "Kabupaten Bolaang Mongondow Utara"},
  {"id": "437", "id_prov": "31", "nama": "Kabupaten Kepulauan Sangihe"},
  {
    "id": "438",
    "id_prov": "31",
    "nama": "Kabupaten Kepulauan Siau Tagulandang Biaro (Sitaro)"
  },
  {"id": "439", "id_prov": "31", "nama": "Kabupaten Kepulauan Talaud"},
  {"id": "440", "id_prov": "31", "nama": "Kota Kotamobagu"},
  {"id": "441", "id_prov": "31", "nama": "Kota Manado"},
  {"id": "442", "id_prov": "31", "nama": "Kabupaten Minahasa"},
  {"id": "443", "id_prov": "31", "nama": "Kabupaten Minahasa Selatan"},
  {"id": "444", "id_prov": "31", "nama": "Kabupaten Minahasa Tenggara"},
  {"id": "445", "id_prov": "31", "nama": "Kabupaten Minahasa Utara"},
  {"id": "446", "id_prov": "31", "nama": "Kota Tomohon"},
  {"id": "447", "id_prov": "32", "nama": "Kabupaten Agam"},
  {"id": "448", "id_prov": "32", "nama": "Kota Bukittinggi"},
  {"id": "449", "id_prov": "32", "nama": "Kabupaten Dharmasraya"},
  {"id": "450", "id_prov": "32", "nama": "Kabupaten Kepulauan Mentawai"},
  {"id": "451", "id_prov": "32", "nama": "Kabupaten Lima Puluh Kota"},
  {"id": "452", "id_prov": "32", "nama": "Kota Padang"},
  {"id": "453", "id_prov": "32", "nama": "Kota Padang Panjang"},
  {"id": "454", "id_prov": "32", "nama": "Kabupaten Padang Pariaman"},
  {"id": "455", "id_prov": "32", "nama": "Kota Pariaman"},
  {"id": "456", "id_prov": "32", "nama": "Kabupaten Pasaman"},
  {"id": "457", "id_prov": "32", "nama": "Kabupaten Pasaman Barat"},
  {"id": "458", "id_prov": "32", "nama": "Kota Payakumbuh"},
  {"id": "459", "id_prov": "32", "nama": "Kabupaten Pesisir Selatan"},
  {"id": "460", "id_prov": "32", "nama": "Kota Sawah Lunto"},
  {"id": "461", "id_prov": "32", "nama": "Kabupaten Sijunjung"},
  {"id": "462", "id_prov": "32", "nama": "Kota Solok"},
  {"id": "463", "id_prov": "32", "nama": "Kabupaten Solok"},
  {"id": "464", "id_prov": "32", "nama": "Kabupaten Solok Selatan"},
  {"id": "465", "id_prov": "32", "nama": "Kabupaten Tanah Datar"},
  {"id": "466", "id_prov": "33", "nama": "Kabupaten Banyuasin"},
  {"id": "467", "id_prov": "33", "nama": "Kabupaten Empat Lawang"},
  {"id": "468", "id_prov": "33", "nama": "Kabupaten Lahat"},
  {"id": "469", "id_prov": "33", "nama": "Kota Lubuk Linggau"},
  {"id": "470", "id_prov": "33", "nama": "Kabupaten Muara Enim"},
  {"id": "471", "id_prov": "33", "nama": "Kabupaten Musi Banyuasin"},
  {"id": "472", "id_prov": "33", "nama": "Kabupaten Musi Rawas"},
  {"id": "473", "id_prov": "33", "nama": "Kabupaten Musi Rawas Utara"},
  {"id": "474", "id_prov": "33", "nama": "Kabupaten Ogan Ilir"},
  {"id": "475", "id_prov": "33", "nama": "Kabupaten Ogan Komering Ilir"},
  {"id": "476", "id_prov": "33", "nama": "Kabupaten Ogan Komering Ulu"},
  {"id": "477", "id_prov": "33", "nama": "Kabupaten Ogan Komering Ulu Selatan"},
  {"id": "478", "id_prov": "33", "nama": "Kabupaten Ogan Komering Ulu Timur"},
  {"id": "479", "id_prov": "33", "nama": "Kota Pagar Alam"},
  {"id": "480", "id_prov": "33", "nama": "Kota Palembang"},
  {
    "id": "481",
    "id_prov": "33",
    "nama": "Kabupaten Penukal Abab Lematang Ilir"
  },
  {"id": "482", "id_prov": "33", "nama": "Kota Prabumulih"},
  {"id": "483", "id_prov": "34", "nama": "Kabupaten Asahan"},
  {"id": "484", "id_prov": "34", "nama": "Kabupaten Batu Bara"},
  {"id": "485", "id_prov": "34", "nama": "Kota Binjai"},
  {"id": "486", "id_prov": "34", "nama": "Kabupaten Dairi"},
  {"id": "487", "id_prov": "34", "nama": "Kabupaten Deli Serdang"},
  {"id": "488", "id_prov": "34", "nama": "Kota Gunungsitoli"},
  {"id": "489", "id_prov": "34", "nama": "Kabupaten Humbang Hasundutan"},
  {"id": "490", "id_prov": "34", "nama": "Kabupaten Karo"},
  {"id": "491", "id_prov": "34", "nama": "Kabupaten Labuhanbatu"},
  {"id": "492", "id_prov": "34", "nama": "Kabupaten Labuhanbatu Selatan"},
  {"id": "493", "id_prov": "34", "nama": "Kabupaten Labuhanbatu Utara"},
  {"id": "494", "id_prov": "34", "nama": "Kabupaten Langkat"},
  {"id": "495", "id_prov": "34", "nama": "Kabupaten Mandailing Natal"},
  {"id": "496", "id_prov": "34", "nama": "Kota Medan"},
  {"id": "497", "id_prov": "34", "nama": "Kabupaten Nias"},
  {"id": "498", "id_prov": "34", "nama": "Kabupaten Nias Barat"},
  {"id": "499", "id_prov": "34", "nama": "Kabupaten Nias Selatan"},
  {"id": "500", "id_prov": "34", "nama": "Kabupaten Nias Utara"},
  {"id": "501", "id_prov": "34", "nama": "Kabupaten Padang Lawas"},
  {"id": "502", "id_prov": "34", "nama": "Kabupaten Padang Lawas Utara"},
  {"id": "503", "id_prov": "34", "nama": "Kota Padang Sidempuan"},
  {"id": "504", "id_prov": "34", "nama": "Kabupaten Pakpak Bharat"},
  {"id": "505", "id_prov": "34", "nama": "Kota Pematang Siantar"},
  {"id": "506", "id_prov": "34", "nama": "Kabupaten Samosir"},
  {"id": "507", "id_prov": "34", "nama": "Kabupaten Serdang Bedagai"},
  {"id": "508", "id_prov": "34", "nama": "Kota Sibolga"},
  {"id": "509", "id_prov": "34", "nama": "Kabupaten Simalungun"},
  {"id": "510", "id_prov": "34", "nama": "Kota Tanjung Balai"},
  {"id": "511", "id_prov": "34", "nama": "Kabupaten Tapanuli Selatan"},
  {"id": "512", "id_prov": "34", "nama": "Kabupaten Tapanuli Tengah"},
  {"id": "513", "id_prov": "34", "nama": "Kabupaten Tapanuli Utara"},
  {"id": "514", "id_prov": "34", "nama": "Kota Tebing Tinggi"},
  {"id": "515", "id_prov": "34", "nama": "Kabupaten Toba Samosir"}
];

class dataKab {
  late int id;
  late String idProv;
  late String nama;

  dataKab({required this.id, required this.idProv, required this.nama});

  dataKab.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    idProv = json['id_prov'];
    nama = json['nama'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['id_prov'] = idProv;
    data['nama'] = nama;
    return data;
  }
}

List<dataKab> dataKabObj = [
  for (var i = 0; i < datakab.length; i++)
    dataKab(id: i, idProv: datakab[i]['id_prov'], nama: datakab[i]['nama'])
];
